### ISSUE TITLE
The explicit call of `setComponentProps` - why and best practices.

### ISSUE THREAD

**Issue by am1006** [skryukov/excellent-palettes#2]
Hi @skryukov 

Great job on `turbo-mount`. It truly solved a problem that exists in one of my projects for a while. Sincerely grateful for this simple yet efficient library.

I was reading the article on Evil Martians and here is the only point that still confuses me 👇

The article suggests to create a Stimulus controller that updates the form field whenever a new color is selected by the user, with the following callback function created:

```javascript
onChange = (color) => {
    this.inputTarget.value = color;
  };
```

Ref: [Highlighted code on "The art of Turbo Mount: Hotwire meets modern JS frameworks"](https://evilmartians.com/chronicles/the-art-of-turbo-mount-hotwire-meets-modern-js-frameworks#:~:text=onChange%20%3D%20(color)%20%3D%3E%20%7B%0A%20%20%20%20this.inputTarget.value%20%3D%20color%3B%0A%20%20%7D%3B)

While checking the code in this repo, I found that [an additional line of code is added](https://github.com/skryukov/excellent-palettes/blob/476964948ca6465e7e0c94f5a1c7242f03c3f465/app/javascript/controllers/turbo_mount_color_picker_controller.js#L14).

```javascript
...
this.setComponentProps({ ...this.componentProps, colors });
...
```

I wonder if this is anything related to manually rerendering the React component, and if this is something you'd encourage us to do when render React components. 

Appreciate your comment and guidance on this!

Cheers,
Leo

**Comment by skryukov** [comment]
Hey, Leo, thanks for kind words!

Yes, you're absolutely right, `setComponentProps` is an [additional helper](https://github.com/skryukov/turbo-mount/blob/c73fc658570f654ddc0b0a316bd0a2dd4ae4494e/packages/turbo-mount/src/turbo-mount-controller.ts#L77-L80) which acts as a replacement for `propsValue=`, but skips the rerendering of the component. Probably I should update the article 😅

**Comment by am1006** [comment]
> Hey, Leo, thanks for kind words!
> 
> Yes, you're absolutely right, `setComponentProps` is an [additional helper](https://github.com/skryukov/turbo-mount/blob/c73fc658570f654ddc0b0a316bd0a2dd4ae4494e/packages/turbo-mount/src/turbo-mount-controller.ts#L77-L80) which acts as a replacement for `propsValue=`, but skips the rerendering of the component. Probably I should update the article 😅

Thanks @skryukov for the quick response. Can I ask why we need to call `this.setComponentProps({ ...this.componentProps, colors });` in the example? Wouldn't the `this.inputTarget.value = color;` be sufficient for the purpose of this callback (`onChange`) function?

**Comment by skryukov** [comment]
Sure! The answer is—we don't need it in this example 😄

It's an optional step that helps sync the dataset props with internal state. You would need this if you want to mutate the dataset outside the component (which will lead to component rerender), i.e., with a Turbo Stream action or via another Stimulus controller.

Something like this:

```js
// application.js
StreamActions.update_turbo_mount_props = function () {
  const component = this.getAttribute("component");
  const dashedComponent = component.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
  const props = JSON.parse(this.getAttribute("props"));
  const el = document.querySelector(`[data-turbo-mount-${dashedComponent}-component-value]`)

  if (el) {
    const origProps = JSON.parse(el.dataset[`turboMount${component}PropsValue`])
    // merge new props:
    el.dataset[`turboMount${component}PropsValue`] = JSON.stringify({...origProps, ...props});
  }
}
```

```ruby
# update_props.turbo_stream.erb
<%= turbo_stream_action_tag :update_turbo_mount_props,
                            component: 'MyComponent',
                            props: { time: Time.current }.to_json %>
```

**Comment by am1006** [comment]
Ah I see - thanks @skryukov! Really appreciate the answer :)
